// This file is generated by scripts/generate_polymarket_semantic_boundary.py.
// Do not edit by hand.

use std::num::NonZeroUsize;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SemanticRoute {
    PostOrder,
    GetExactOrder,
    GetAssociatedTrades,
}

impl SemanticRoute {
    #[must_use]
    pub const fn method(self) -> &'static str {
        match self {
            Self::PostOrder => "POST",
            Self::GetExactOrder => "GET",
            Self::GetAssociatedTrades => "GET",
        }
    }

    #[must_use]
    pub const fn path(self) -> &'static str {
        match self {
            Self::PostOrder => "/order",
            Self::GetExactOrder => "/data/order/{order_id}",
            Self::GetAssociatedTrades => "/data/trades",
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct WireValueError {
    pub route: SemanticRoute,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum PostOrderStatus {
    Live,
    Matched,
    Delayed,
    Unmatched,
}

impl TryFrom<&str> for PostOrderStatus {
    type Error = WireValueError;

    fn try_from(value: &str) -> Result<Self, Self::Error> {
        match value {
            "live" => Ok(Self::Live),
            "matched" => Ok(Self::Matched),
            "delayed" => Ok(Self::Delayed),
            "unmatched" => Ok(Self::Unmatched),
            _ => Err(WireValueError {
                route: SemanticRoute::PostOrder,
            }),
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ExactOrderStatus {
    Live,
    Invalid,
    CanceledMarketResolved,
    Canceled,
    Matched,
}

impl TryFrom<&str> for ExactOrderStatus {
    type Error = WireValueError;

    fn try_from(value: &str) -> Result<Self, Self::Error> {
        match value {
            "ORDER_STATUS_LIVE" => Ok(Self::Live),
            "ORDER_STATUS_INVALID" => Ok(Self::Invalid),
            "ORDER_STATUS_CANCELED_MARKET_RESOLVED" => Ok(Self::CanceledMarketResolved),
            "ORDER_STATUS_CANCELED" => Ok(Self::Canceled),
            "ORDER_STATUS_MATCHED" => Ok(Self::Matched),
            _ => Err(WireValueError {
                route: SemanticRoute::GetExactOrder,
            }),
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum AssociatedTradeStatus {
    Matched,
    Mined,
    Confirmed,
    Retrying,
    Failed,
}

impl TryFrom<&str> for AssociatedTradeStatus {
    type Error = WireValueError;

    fn try_from(value: &str) -> Result<Self, Self::Error> {
        match value {
            "MATCHED" => Ok(Self::Matched),
            "MINED" => Ok(Self::Mined),
            "CONFIRMED" => Ok(Self::Confirmed),
            "RETRYING" => Ok(Self::Retrying),
            "FAILED" => Ok(Self::Failed),
            _ => Err(WireValueError {
                route: SemanticRoute::GetAssociatedTrades,
            }),
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SemanticVocabulary {
    Side,
    OrderType,
    TraderSide,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct VocabularyValueError {
    pub vocabulary: SemanticVocabulary,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ProviderSide {
    Buy,
    Sell,
}

impl TryFrom<&str> for ProviderSide {
    type Error = VocabularyValueError;

    fn try_from(value: &str) -> Result<Self, Self::Error> {
        match value {
            "BUY" => Ok(Self::Buy),
            "SELL" => Ok(Self::Sell),
            _ => Err(VocabularyValueError {
                vocabulary: SemanticVocabulary::Side,
            }),
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ProviderOrderType {
    Gtc,
    Fok,
    Gtd,
    Fak,
}

impl TryFrom<&str> for ProviderOrderType {
    type Error = VocabularyValueError;

    fn try_from(value: &str) -> Result<Self, Self::Error> {
        match value {
            "GTC" => Ok(Self::Gtc),
            "FOK" => Ok(Self::Fok),
            "GTD" => Ok(Self::Gtd),
            "FAK" => Ok(Self::Fak),
            _ => Err(VocabularyValueError {
                vocabulary: SemanticVocabulary::OrderType,
            }),
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ProviderTraderSide {
    Taker,
    Maker,
}

impl TryFrom<&str> for ProviderTraderSide {
    type Error = VocabularyValueError;

    fn try_from(value: &str) -> Result<Self, Self::Error> {
        match value {
            "TAKER" => Ok(Self::Taker),
            "MAKER" => Ok(Self::Maker),
            _ => Err(VocabularyValueError {
                vocabulary: SemanticVocabulary::TraderSide,
            }),
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SemanticLimitKind {
    RequestBodyBytes,
    RequestItems,
    ResponseBodyBytes,
    ResponseItems,
    TransactionHashes,
    TradeIds,
    AssociatedTrades,
    StringBytes,
    DecimalBytes,
    LogItems,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SemanticLimitError {
    Zero(SemanticLimitKind),
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct SemanticLimitValues {
    pub request_body_bytes: usize,
    pub request_items: usize,
    pub response_body_bytes: usize,
    pub response_items: usize,
    pub transaction_hashes: usize,
    pub trade_ids: usize,
    pub associated_trades: usize,
    pub string_bytes: usize,
    pub decimal_bytes: usize,
    pub log_items: usize,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct SemanticLimits {
    request_body_bytes: NonZeroUsize,
    request_items: NonZeroUsize,
    response_body_bytes: NonZeroUsize,
    response_items: NonZeroUsize,
    transaction_hashes: NonZeroUsize,
    trade_ids: NonZeroUsize,
    associated_trades: NonZeroUsize,
    string_bytes: NonZeroUsize,
    decimal_bytes: NonZeroUsize,
    log_items: NonZeroUsize,
}

impl SemanticLimits {
    pub const fn checked(values: SemanticLimitValues) -> Result<Self, SemanticLimitError> {
        Ok(Self {
            request_body_bytes: match NonZeroUsize::new(values.request_body_bytes) {
                Some(value) => value,
                None => {
                    return Err(SemanticLimitError::Zero(
                        SemanticLimitKind::RequestBodyBytes,
                    ));
                }
            },
            request_items: match NonZeroUsize::new(values.request_items) {
                Some(value) => value,
                None => return Err(SemanticLimitError::Zero(SemanticLimitKind::RequestItems)),
            },
            response_body_bytes: match NonZeroUsize::new(values.response_body_bytes) {
                Some(value) => value,
                None => {
                    return Err(SemanticLimitError::Zero(
                        SemanticLimitKind::ResponseBodyBytes,
                    ));
                }
            },
            response_items: match NonZeroUsize::new(values.response_items) {
                Some(value) => value,
                None => return Err(SemanticLimitError::Zero(SemanticLimitKind::ResponseItems)),
            },
            transaction_hashes: match NonZeroUsize::new(values.transaction_hashes) {
                Some(value) => value,
                None => {
                    return Err(SemanticLimitError::Zero(
                        SemanticLimitKind::TransactionHashes,
                    ));
                }
            },
            trade_ids: match NonZeroUsize::new(values.trade_ids) {
                Some(value) => value,
                None => return Err(SemanticLimitError::Zero(SemanticLimitKind::TradeIds)),
            },
            associated_trades: match NonZeroUsize::new(values.associated_trades) {
                Some(value) => value,
                None => {
                    return Err(SemanticLimitError::Zero(
                        SemanticLimitKind::AssociatedTrades,
                    ));
                }
            },
            string_bytes: match NonZeroUsize::new(values.string_bytes) {
                Some(value) => value,
                None => return Err(SemanticLimitError::Zero(SemanticLimitKind::StringBytes)),
            },
            decimal_bytes: match NonZeroUsize::new(values.decimal_bytes) {
                Some(value) => value,
                None => return Err(SemanticLimitError::Zero(SemanticLimitKind::DecimalBytes)),
            },
            log_items: match NonZeroUsize::new(values.log_items) {
                Some(value) => value,
                None => return Err(SemanticLimitError::Zero(SemanticLimitKind::LogItems)),
            },
        })
    }

    #[must_use]
    pub const fn request_body_bytes(self) -> usize {
        self.request_body_bytes.get()
    }

    #[must_use]
    pub const fn request_items(self) -> usize {
        self.request_items.get()
    }

    #[must_use]
    pub const fn response_body_bytes(self) -> usize {
        self.response_body_bytes.get()
    }

    #[must_use]
    pub const fn response_items(self) -> usize {
        self.response_items.get()
    }

    #[must_use]
    pub const fn transaction_hashes(self) -> usize {
        self.transaction_hashes.get()
    }

    #[must_use]
    pub const fn trade_ids(self) -> usize {
        self.trade_ids.get()
    }

    #[must_use]
    pub const fn associated_trades(self) -> usize {
        self.associated_trades.get()
    }

    #[must_use]
    pub const fn string_bytes(self) -> usize {
        self.string_bytes.get()
    }

    #[must_use]
    pub const fn decimal_bytes(self) -> usize {
        self.decimal_bytes.get()
    }

    #[must_use]
    pub const fn log_items(self) -> usize {
        self.log_items.get()
    }
}

pub const TRANSACTION_HASH_BYTES: usize = 32;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum UnavailableCapability {
    PermanentTerminality,
    CompleteCapture,
    CompetingWorkAbsence,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct CapabilityEvidence {
    pub capability: UnavailableCapability,
    pub reason: &'static str,
}

pub const CURRENT_V2_UNAVAILABLE: [CapabilityEvidence; 3] = [
    CapabilityEvidence {
        capability: UnavailableCapability::PermanentTerminality,
        reason: "no_indefinite_linearizable_exact_hash_tombstone",
    },
    CapabilityEvidence {
        capability: UnavailableCapability::CompleteCapture,
        reason: "no_complete_bounded_transaction_hash_contract",
    },
    CapabilityEvidence {
        capability: UnavailableCapability::CompetingWorkAbsence,
        reason: "no_competing_nonce_or_provider_work_exclusion",
    },
];

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct RegisteredSource {
    pub id: &'static str,
    pub repository: &'static str,
    pub commit: &'static str,
    pub path: &'static str,
    pub blob: &'static str,
    pub authority: &'static str,
}

pub const REGISTERED_SOURCES: [RegisteredSource; 10] = [
    RegisteredSource {
        id: "bolt_architecture",
        repository: "seungpyoson/bolt-v2",
        commit: "fe368f851aae33a064cf0157a1a03ed5e3092a21",
        path: "docs/superpowers/specs/2026-07-15-autonomous-operation-migration-pr-contract.md",
        blob: "39702ab6cb19514b8af382d57f86e35e096b0e4d",
        authority: "semantic_contract",
    },
    RegisteredSource {
        id: "typescript_routes",
        repository: "Polymarket/clob-client-v2",
        commit: "ff5913f83132a141e01d403e505b6ccc003aa0f7",
        path: "src/endpoints.ts",
        blob: "88768ab142024c8c96df2c7b9a7feeec81baacfe",
        authority: "provider_route_evidence",
    },
    RegisteredSource {
        id: "typescript_schema",
        repository: "Polymarket/clob-client-v2",
        commit: "ff5913f83132a141e01d403e505b6ccc003aa0f7",
        path: "src/types/clob.ts",
        blob: "7384b7727d9b73743b987ebaf0d95815b233c29d",
        authority: "provider_schema_evidence",
    },
    RegisteredSource {
        id: "typescript_side",
        repository: "Polymarket/clob-client-v2",
        commit: "ff5913f83132a141e01d403e505b6ccc003aa0f7",
        path: "src/order-utils/model/side.ts",
        blob: "4c1eccd3242b42ec5a0344673703cff27b72a355",
        authority: "provider_schema_evidence",
    },
    RegisteredSource {
        id: "rust_vocabulary",
        repository: "Polymarket/rs-clob-client-v2",
        commit: "3ae1aae5e9ded38f984464c9fc0f307f8a9f41fb",
        path: "src/clob/types/mod.rs",
        blob: "310d8091afd65526d4dbcd2ba0c01fc554b94688",
        authority: "independent_comparison_evidence",
    },
    RegisteredSource {
        id: "rust_schema",
        repository: "Polymarket/rs-clob-client-v2",
        commit: "3ae1aae5e9ded38f984464c9fc0f307f8a9f41fb",
        path: "src/clob/types/response.rs",
        blob: "b6dbe326134b9b48f7283eb19f0b65eb10297420",
        authority: "independent_comparison_evidence",
    },
    RegisteredSource {
        id: "python_routes",
        repository: "Polymarket/py-clob-client-v2",
        commit: "fdb2590dc85e600ad98f1f668ea62a0627554d73",
        path: "py_clob_client_v2/endpoints.py",
        blob: "9980baf5861374c4c70f36da5213848e142b6493",
        authority: "independent_comparison_evidence",
    },
    RegisteredSource {
        id: "python_schema",
        repository: "Polymarket/py-clob-client-v2",
        commit: "fdb2590dc85e600ad98f1f668ea62a0627554d73",
        path: "py_clob_client_v2/clob_types.py",
        blob: "fa39f66752ce908aafc044f27d3624cda1a2fd5d",
        authority: "independent_comparison_evidence",
    },
    RegisteredSource {
        id: "exchange_order_state",
        repository: "Polymarket/ctf-exchange-v2",
        commit: "ccc0596074f4dfd62c944fbca4de252893b82b4b",
        path: "src/exchange/libraries/Structs.sol",
        blob: "0bbcd991063772a864bfe4c51679b7d589559d76",
        authority: "provider_contract_evidence",
    },
    RegisteredSource {
        id: "exchange_fill_effect",
        repository: "Polymarket/ctf-exchange-v2",
        commit: "ccc0596074f4dfd62c944fbca4de252893b82b4b",
        path: "src/exchange/interfaces/ITrading.sol",
        blob: "4ea517d5808972e224255981d60d75049ac72032",
        authority: "provider_contract_evidence",
    },
];
